services:
  - type: web
    name: streamlit-app
    runtime: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: streamlit run app.py
    env: python
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.1  # Pastikan versi Python sesuai
